name: Build

on: push

permissions:
  issues: write
  checks: write
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "⬇️ Checkout"
        uses: actions/checkout@v3
      - name: Semantic Release
        id: get-next-version
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          dry_run: true
          extra_plugins: |
            conventional-changelog-conventionalcommits 
            @semantic-release/github 
            @semantic-release/changelog 
            semantic-release-export-data

      - name: "Package and Publish"
        if: ${{ steps.get-next-version.outputs.new_release_published == 'true'  }}
        run: cd src && zip -r ../MezacraftS3-${{ steps.get-next-version.outputs.new_release_version }}.zip *
      - name: "Save SHA1 hash of the file"
        if: ${{ steps.get-next-version.outputs.new_release_published == 'true'  }}
        run: |
          SHA="$(sha1sum MezacraftS3-${{ steps.get-next-version.outputs.new_release_version }}.zip | cut -d ' ' -f 1)"
          echo $SHA > "MezacraftS3-${{ steps.get-next-version.outputs.new_release_version }}.zip.sha1"
          echo $SHA >> $GITHUB_STEP_SUMMARY
      - name: Semantic Release
        if: ${{ steps.get-next-version.outputs.new_release_published == 'true'  }}
        id: release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          extra_plugins: |
            conventional-changelog-conventionalcommits 
            @semantic-release/github 
            @semantic-release/changelog 
            semantic-release-export-data
      - uses: wolfigster/rcon-action@v1.0.4
        if: ${{ steps.get-next-version.outputs.new_release_published == 'true'  }}
        with:
          server: 'minecraft.meza.gg'
          port: '25575'
          password: ${{ secrets.RCON_PASSWORD }}
          commands: '["pack set \"https://github.com/meza/MezacraftS3-resource-pack/releases/download/v${{ steps.get-next-version.outputs.new_release_version }}/MezacraftS3-${{ steps.get-next-version.outputs.new_release_version }}.zip\" push"]'
